#!/bin/bash
FILEDIR=$(rlrecurse "*" | grep -P "(?<=\/)$1") # Needs to match a little better

echo "FILEDIR: $FILEDIR"
FILEFORMAT=$(echo "$FILEDIR" | grep -P -o "(?<=\.)[\w\d]+")
echo "FILEFORMAT REGEX: $FILEFORMAT"
case "$FILEFORMAT" in
    "jpg") 
	echo "~~~JPG~~~"
	RPFNAME="currentwallpaper.jpg"
	;;
    "png") 
	echo "~~~PNG~~~"
	RPFNAME="currentwallpaper.png"
	;;
    "jpeg")
	echo "~~~JPEG~~~"
	RPFNAME="currentwallpaper.jpeg"
	;;
esac 
echo "FILEFORMAT: $RPFNAME"
rm ~/wallpapers/currentwallpaper.*
if [[ -z $RPFNAME ]]
then 
    echo "error 101: no file address"
    exit
fi
cp $FILEDIR ~/wallpapers/$RPFNAME # Will break if its any other format.
echo $1 > ~/wallpapers/previousname

feh --bg-scale ~/wallpapers/$RPFNAME
